version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=9907811   # change this to your ID
       - API_HASH=b5adb7f7d4a096750edec1bc6daacd56 # change this to your HASH
       - BOT_TOKEN=7296554944:AAGKY1DzFRVv842nGpIcu54g34qmb697E_8 #TGFileDownloadBot
       - BIN_CHANNEL=-1002238166707 # paste channel ID
      ports:
       - 127.0.0.1:8000:80
      volumes:
       - $HOME/TG-FileStreamBot:/app/.env
